
import __ASTRO_IMAGE_IMPORT_WDgjs from "./screenshots/ipconfig.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvirtualbox-static-ip-linux.md";
import __ASTRO_IMAGE_IMPORT_QLyD2 from "./screenshots/lvm_structure.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fresize-extend-logical-volume-oracle-linux-7.md";
import __ASTRO_IMAGE_IMPORT_uECIp from "./screenshots/math.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvirtualbox-static-ip-linux.md";
import __ASTRO_IMAGE_IMPORT_1IDs7q from "./screenshots/virtualbox_gui.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvirtualbox-static-ip-linux.md";
import __ASTRO_IMAGE_IMPORT_ZHIYlY from "./screenshots/vm_1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvirtualbox-static-ip-linux.md";
import __ASTRO_IMAGE_IMPORT_o2Qhc from "./screenshots/vm_2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvirtualbox-static-ip-linux.md";
import __ASTRO_IMAGE_IMPORT_1uOGUn from "./screenshots/vm_3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvirtualbox-static-ip-linux.md";
import __ASTRO_IMAGE_IMPORT_Z2szAfn from "./screenshots/vm_4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvirtualbox-static-ip-linux.md";
import __ASTRO_IMAGE_IMPORT_Z1lMJBc from "./screenshots/vm_5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvirtualbox-static-ip-linux.md";
export default new Map([["./screenshots/ipconfig.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvirtualbox-static-ip-linux.md", __ASTRO_IMAGE_IMPORT_WDgjs], ["./screenshots/lvm_structure.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fresize-extend-logical-volume-oracle-linux-7.md", __ASTRO_IMAGE_IMPORT_QLyD2], ["./screenshots/math.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvirtualbox-static-ip-linux.md", __ASTRO_IMAGE_IMPORT_uECIp], ["./screenshots/virtualbox_gui.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvirtualbox-static-ip-linux.md", __ASTRO_IMAGE_IMPORT_1IDs7q], ["./screenshots/vm_1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvirtualbox-static-ip-linux.md", __ASTRO_IMAGE_IMPORT_ZHIYlY], ["./screenshots/vm_2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvirtualbox-static-ip-linux.md", __ASTRO_IMAGE_IMPORT_o2Qhc], ["./screenshots/vm_3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvirtualbox-static-ip-linux.md", __ASTRO_IMAGE_IMPORT_1uOGUn], ["./screenshots/vm_4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvirtualbox-static-ip-linux.md", __ASTRO_IMAGE_IMPORT_Z2szAfn], ["./screenshots/vm_5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvirtualbox-static-ip-linux.md", __ASTRO_IMAGE_IMPORT_Z1lMJBc]]);
		